apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-django-k8s-postgres
spec:
  selector:
    matchLabels:
      app: try-django-k8s-postgres
  template:
    metadata:
      labels:
        app: try-django-k8s-postgres
    spec:
      containers:
        - name: try-django-k8s-postgres
          image: postgres:13.0-alpine
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pg-vol"
      volumes:
        - name: pg-vol
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: try-django-k8s-postgres-svc
spec:
  selector:
    app: try-django-k8s-postgres
  ports:
  - port: 5432
    targetPort: 5432
