apiVersion: v1
kind: PersistentVolume
metadata:
  name: dj-nginx-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: try-django-k8s-dj-nginx-sc
  hostPath:
    path: /mnt/try-django-k8s/dj-nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dj-nginx-pvc
spec:
  storageClassName: try-django-k8s-dj-nginx-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi



---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: try-django-k8s-postgres-sc
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/try-django-k8s/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: try-django-k8s-postgres-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi