apiVersion: apps/v1
kind: Deployment
metadata:
  name: try-django-k8s-redis
spec:
  selector:
    matchLabels:
      app: try-django-k8s-redis
  template:
    metadata:
      labels:
        app: try-django-k8s-redis
    spec:
      containers:
        - name: try-django-k8s-redis
          image: redis:7.0.5-alpine
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: try-django-k8s-redis-svc
spec:
  selector:
    app: try-django-k8s-redis
  ports:
  - port: 6379
    targetPort: 6379
